### ISSUE TITLE
NOOBS Lite - "Available 0 MB" - cannot install software

### ISSUE THREAD

**Issue by redhawkuk** [raspberrypi/noobs#174] opened 2014-01-24 10:38 UTC
Full description can be found at - http://www.raspberrypi.org/phpBB3/viewtopic.php?f=63&t=67449
I have a Pi early rev 1 board, I've been trying to install software using NOOBS Lite using a 8GB Micro SD+adapter.
I have formatted the card according to help instructions but when I come to install software I have Available 0 MB.
I also appear to have a hidden dialogue box which I had to dismiss with the Enter key before enabling PAL mode.
It could be related but since NOOBS is forced to boot up in HDMI only mode I do not know what it reads.
I've tried earlier versions of NOOBS Lite and another SD Card but still the same problem with missing card space.

**Comment by caderoux** [comment] 2015-01-13 06:48
It looks like this is still generally a problem?  I have a Mac (OSX Yosemite) and decided to look at NOOBS for one of my new RPis (the card is a 16GB Kingston).  I used the SD card formatter to wipe the card.  I unzipped the files (1.3.11) and then ejected the card and put it in the RPi and got the popup about the FAT mismatch.

**Comment by lurch** [comment] 2015-01-13 18:06
@caderoux Are you using a SD card-reader built into your Mac, or are you using a USB card-reader? Do you have a different card reader you could use/borrow to see if that gives different results? Does the card-reader that gives you problems give you NOOBS errors *every* time after using SDFormatter?

My current understanding of the issue is that there's some "internal flags" in the FAT32 filesystem header which don't get fully updated when the card is ejected, and parted then spots this and complains. But I've yet to determine why some people get the error and most people don't (I've never had it myself).

**Comment by caderoux** [comment] 2015-01-13 18:54
@lurch I am using this reader (http://www.amazon.com/gp/product/B003XKWLSS) plugged in USB, but I will try to use the builtin reader or another PC in the house and will update ehre with my findings.

**Comment by caderoux** [comment] 2015-01-14 04:57
@lurch I switched to the same card in an SD card adaptor using the builtin reader and it worked fine (fresh format with SD card formatter for good measure).

**Comment by procount** [comment] 2015-01-14 13:26
@lurch In my partition reversion exercises, I found that shrinking the partition, expanding it again and then shrinking a 2nd time sometimes resulted in the FAT table mismatch and sometimes it complained about a file cluster being located outside of the partition. Often the expansion resulted in unmet constraints too, or an assertion failure of headsize being >63. I wasn't sure why both sfdisk and parted were being used to partition the drive - maybe to work around some limitations of parted 2.3? That's why I upgraded to parted 2.4. Maybe that would alleviate some of these errors? Also preventing the FAT partition from being less than 256MB in size might help.

**Comment by procount** [comment] 2015-01-14 13:39
Anyone having this problem with NOOBS-lite could try adding a dummy file to the NOOBS SD card before inserting it into the RPi. This dummy file should be at least 200MB in size to ensure that after the partition is shrunk by NOOBS, it is still >256MB. Please report if this makes a difference. Has anyone experienced this issue with the FULL NOOBS version, i.e. when they have the Raspbian OS copied to the SD card ready for installation?

**Comment by caderoux** [comment] 2015-01-14 15:23
@procount I was/am using full NOOBS.  I will try some other experiments with both the SD adaptor and the USB reader like using the dummy file.  I will be sure to use SD formatter before each run.

**Comment by lurch** [comment] 2015-01-14 15:43
@caderoux So do you *always* get the error consistently when using your 16GB card in your USB card reader, but never when using the same card in your built-in card reader? Do you always get the same error using the same card and same USB card reader on a different computer / OS? Do you always get the same error when using the USB card reader on your Mac with other SD cards, or only with your 16GB card? Do you get the same error with both full NOOBS and NOOBS lite?

Sorry for all the questions, but it would be great to be able to narrow down the exact circumstances which do and don't cause the problem...

**Comment by caderoux** [comment] 2015-01-14 16:12
@lurch It was consistent on the USB card reader with that card on the Mac.  I will try it on a PC as well.

**Comment by hebbers** [comment] 2015-01-14 20:13
Hi there, just purchased a RPI and I'm having the same issue, where the available space is 0MB, so I can't install an OS. I'm using a Mac and have reformatted the 8GB card (using SDFormatter) and copied across Noobs (full version) a number of times - but always get the same message. I'm using a Sandisk microSD adapter and the card is Kinston. I also have a 64GB micro USB but just read somewhere that the RPI only supports up to 32GB.

Any thoughts on how I can resolve this - would be much appreciated!? I'm new to Linux and not a developer.

![20150114_200553_resized](https://cloud.githubusercontent.com/assets/10536762/5746725/81f3c88e-9c29-11e4-9c49-206ce6195fec.jpg)

**Comment by lurch** [comment] 2015-01-14 22:25
I've never experienced the problem myself, but other people above have said that renaming the card can be enough of a 'tweak' to update the FAT structures so that the problem goes away. Or if that doesn't work, you could try adding a small file to the card (after writing NOOBS to it) to see if that has the same filesystem-internals updating effect.

The Raspberry Pi works fine with 64GB SD / microSD cards **if** you reformat them to FAT32 first. The trouble is that according to the "official SD specs" cards above 32GB are supposed to be formatted as exFAT, and so that's the only option that the official SDFormatter gives you :-(  If you can use a 3rd-party formatting tool to format the card as FAT32 (I don't have a Mac so can't make any recommendations), then you should be good to go. There's more info about this [here](https://github.com/raspberrypi/documentation/pull/88).

**Comment by mRotten** [comment] 2015-02-21 07:09
I'm having this same problem with my Raspberry Pi 2. It happens with both of two ScanDisk microSD cards after reformatting FAT32 using the SD tool, both with and without a volume label. Same results each time; "Error resizing existing FAT partition", then when I dismiss that window, I get another window with the OS choices that says there's no space available.

**Comment by lurch** [comment] 2015-02-21 13:23
Yeah, sounds like altering the "sharing permissions" is just another way of tweaking the internal-FAT-structures just enough to make the problem go away. I believe for the volume-label tweak to work, you probably need to add/rename the volume label *after* writing NOOBS files to your SD card.

I've still not been able to reproduce this myself (which would be required for me to be able to add (and test!) a fix for this to NOOBS), and it seems that as soon as someone has a successful-workaround for this problem, they stop participating in the discussion here; which is good for them but not very helpful for me ;-)

**Comment by mcclumpherty** [comment] 2015-03-11 00:14
I think that I have found the solution to this.  I have been tearing my hair out with it all night.

I received my Pi 2 from thepihut.com today and it arrived with an 8GB SD card pre-loaded with NOOBS.  I merrily proceeded to install Rasbian and OpenElec which went through nicely and I was able to play with Kodi for an hour or so.  However, I screwed it up and decided to re-install everything from scratch but this time to use a 32GB SD card instead.

At this point, I copied the files over from the 8GB SD card onto the 32GB one.

This is where I started getting the 0MB available problem that everyone else has been having.  In vain, I tried everything that has been suggested here - using the sdcard.org formatter, using Windows, using Linux, renaming the partition and sharing the partition - all to no avail.

Eventually, I wondered whether there was something askew with the actual files on the 8GB card.  I then decided to download the NOOBS files again from the raspberrypi.org website, removed all the partitions from the 32GB card (using the gnome disk tool in linux), created a 2GB partition, left the partition name blank and copied the freshly downloaded files into the 2GB partition.

I then powered up the Pi and lo-and-behold I see 29 or so GB of available space and I am now installing Raspian and OpenElec onto the 32GB card.

It seems that after the initial install, and after the re-partitioning, something changes in the NOOBS files in it to prevent it being used as an installation partition.

Well, at least that's my tuppenceworth.

Archie

**Comment by lurch** [comment] 2015-03-11 02:27
@mcclumpherty Your issue is in fact different to everybody else's, and is in fact *because* you'd copied the files directly from one card to another card (rather than following the official instructions).
This means that `runinstaller` wasn't present in `recovery.cmdline` (see #19 for more info about that), and thus your first partition won't have been resized to make space for the OSes to install into.

**Comment by ACRHOME** [comment] 2015-04-17 12:37
Hi Guys,
I found the solution already. Please format your SD card with SDFORMART Software and remember to set the option setting is 
Format Type : FULL(OverWrite)
Format Size Adjustment : ON
Volume label is blank.
after that you can copy the installation files to SD card.
Goodluck!
Andy NGuyen

**Comment by lurch** [comment] 2015-04-17 12:48
@ACRHOME What you describe is already in the official [instructions](https://www.raspberrypi.org/documentation/installation/noobs.md) and I'm sure everyone in this thread had already tried that first.

**Comment by stunney** [comment] 2015-04-21 13:32
I did the above instructions.  What *actually* fixed this issue for me was to "safely remove" the SDHC card via the Windows Status Bar icon as described by lurch last January.

**Comment by dempsone** [comment] 2015-04-22 04:24
Hi All,

Wondering you guys can help.

I am having the same issues as above, I have done all the troubleshooting provided with no luck

I am getting Error: Unable to satisfy all constraints on the partition.

Is it because my SD card is a few meg smaller? should be 8GB but it was bought off ebay

When i resize 1 8192s 143M

p shows

Number        Start        End         Size         Type       File System
1                   4194KB   7904MB   7900MB  Primary    fat32

**Comment by lurch** [comment] 2015-04-22 09:36
@dempsone Your issue is different to the one being discussed here, so please open a new issue (to avoid overlap and confusion) and I'll do what I can to help.

**Comment by pfeerick** [comment] 2015-05-17 05:15
I can confirm that redhawkuk's suggested fix from Jan 25, 2014 of setting a volume label works. I just used noobs v1.4.1 offline to provision a new Raspberry Pi B+ with a brand new 8GB Sandisk microSD, and that was the apparent culprit to my problem. 

I formatted the card with the SD Association format utility (w/ size adjustment on), copied the Noob v1.4.1 offline install files onto the microSD, safely removed the card, booted up the pi, and got a error message saying something about a cluster size (reporting one cluster smaller than expected). OK'd that message, and then had 0MB of free space and couldn't install anything. 

Inserted the card back into the Windows computer, set a creative volume label of '8GB', safely removed and restarted pi. Problem gone, and noobs happily installing Rasbian as I type...

**Comment by mhorton92586** [comment] 2015-08-17 22:39
Thank you so much, mRotten!  I tried everything on this site and several others.  Finally, what worked was changing the permissions!  Thank you, thank you, thank you!

**Comment by dasrecht** [comment] 2015-08-20 08:19
Thanks @lurch!

> Yeah, sounds like altering the "sharing permissions" is just another way of tweaking the internal-FAT-structures just enough to make the problem go away. I believe for the volume-label tweak to work, you probably need to add/rename the volume label after writing NOOBS files to your SD card.

That helped for me on OSX. After several tries i just renamed the volume and it worked without any further issues. Should we probably add this to the Readme to have it handy when users run into the problem?

**Comment by ccanepa** [comment] 2015-11-12 18:20
I found the same problem with NOOBS 1.4.2 and raspi2, and the suggestion from redhawkuk (setting some volume label) worked for me.

A simple
```
>label n: noobs142
```
from a Windows cmd console, where 'n' the unit seen for the SD in explorer, worked fine, no need to reformat or anything.

**Comment by Paul6677** [comment] 2015-11-17 16:30
"Yeah, that's what I suspected might happen. I think the "NOOBS doesn't boot when no volume label is set" is actually a red herring, and the action of setting a volume label (after the NOOBS files have been written to the card) does "just enough" to modify the filesystem, so that parted is then able to resize the partitions."

This worked for me.  You have to relabel the drive after transferring the NOOBS files.

**Comment by XECDesign** [comment] 2018-03-07 14:08
Unclear what the issue is and no activity. Sounds like this isn't a problem when SD Formatter is used. Please re-open with a clear summary of the problem if this is still an issue.

**Closed by XECDesign** 2018-03-07 14:08 UTC
Labels: in-progress, initial-boot
