### ISSUE TITLE
Feature Request: Skip Noobs Screen

### ISSUE THREAD

**Issue by cawoodm** [raspberrypi/noobs#368] opened 2017-01-04 07:18 UTC
This is related to http://raspberrypi.stackexchange.com/questions/59154/
Allow skip of Noobs screen (Shift will get you there anyway) without any delay or prompt.

Also, show that this is, in fact, Noobs somewhere on the screen

**Comment by lurch** [comment] 2017-01-04 14:36
Duplicate of #168 ?

**Comment by procount** [comment] 2017-01-06 00:23
Have a look at my response in #168. Not quite as you want yet, but nearly there. Comments?

**Comment by procount** [comment] 2017-01-06 13:30
Now implemented with no delay or prompt in test version of pinn-212b.zip (see #168)

**Comment by procount** [comment] 2017-01-10 14:37
Now implemented in released PINN p2.1.2

**Closed** 2017-11-03 14:39 UTC
Labels: duplicate
