### ISSUE TITLE
Format just a system

### ISSUE THREAD

**Issue by chenteparao** [raspberrypi/noobs#580] opened 2020-04-09 01:25 UTC
Hi all, I am very new in NOOBS

I have three systems in my sd card, but I crash just one, can I only format that system through noobs or need start again with three?

**Comment by procount** [comment] 2020-04-09 08:15
You have several options, depending on your experience and inclination:
1. NOOBS does not have the facility to replace just one OS, so you would need to start again and install all 3 OSes again.
2. You could replace your single OS manually by downloading the install files for it and extracting the files over your crashed system. You then need to fix up the partition references manually by editing cmdline.txt and /etc/fstab. (There may be additional steps depending on which OS you are referring to, but since you installed with NOOBS, I doubt there will be any).
3. You could replace NOOBS with PINN, which is a compatible fork of NOOBS. This has the ability to backup, restore, replace and reinstall individual OSes. I wrote a post on how to do it somewhere, if only I could find it!

**Comment by chenteparao** [comment] 2020-04-09 13:49
Thank You man, I think I go for pinn.

**Comment by lurch** [comment] 2020-04-09 14:03
Closing issue, as this is something that NOOBS doesn't support (and it sounds like the user has a workaround).

**Closed by lurch** 2020-04-09 14:03 UTC

**Comment by lurch** [comment] 2020-04-09 14:07
This is also a duplicate of #193  :wink:

**Comment by procount** [comment] 2020-04-09 14:33
@chenteparao - Can't find my post, but this one is close enough -> https://github.com/procount/pinn/issues/108
