### ISSUE TITLE
0 MB Diskspace, unable to install an OS.

### ISSUE THREAD

**Issue by Ferdies** [raspberrypi/noobs#277] opened 2015-09-05 19:26 UTC
I'm currently struggling to install an OS on my Raspberry Pi 2, it says 0 MB Diskspace and won't let me install anything I have an 8GB SD card, with Noobs on it, however, it still isn't working, can someone please help me? 

Thanks,
Ferdies

**Comment by lurch** [comment] 2015-10-21 13:35
Which particular card do you have? Did you format it using SDFormatter?

This *may* be a duplicate of #258 or #174

**Comment by XECDesign** [comment] 2018-01-30 14:09
No reply

**Closed by XECDesign** 2018-01-30 14:09 UTC
Labels: initial-boot
