### ISSUE TITLE
missing build dependancy

### ISSUE THREAD

**Issue by plughplover** [raspberrypi/noobs#275] opened 2015-07-31 00:04 UTC
README.md says:

sudo apt-get install build-essential rsync texinfo libncurses-dev whois unzip

After 12+ hours chugging away on my pi2, build failed.
Investigation revealed the need to add 'qt4-linguist-tools'
(very early on I also ran into a need for package 'bc'.)

Given BUILDME.sh deletes output/build when invoked, the missing qt4 bit was a real pisser.

**Comment by lurch** [comment] 2015-07-31 00:16
Duplicate of #158  (which I've unfortunately still been too busy to fix yet).

> Given BUILDME.sh deletes output/build when invoked, the missing qt4 bit was a real pisser.

Erm, no it doesn't. Unless you can show me where?

Given the relatively 'weedy' CPU of a Raspberry Pi (even a Raspberry Pi 2), it's much better to just build NOOBS on a regular x86 Linux PC - it'll take you *much* less than 12 hours. NOOBS is based around buildroot, which means even running BUILDME.sh on a PC with an x86 CPU will create output files that run on the ARM CPU of the Raspberry Pi.

**Closed by lurch** 2015-07-31 00:16 UTC
Labels: duplicate
