### ISSUE TITLE
Plug in network cable during initial setup causes installer to stop

### ISSUE THREAD

**Issue by Ruffio** [raspberrypi/noobs#261] opened 2015-05-16 06:53 UTC
I just received my Pi and pluged in keyboard, mouse HDMI and power.

I chose Raspbian (first option) to be installed. It continued with the progress bar and chaning hints. I found out that I had forgotten to plugin my network cable so I did that about 40-50 %. The installer seemed to stop and I could only see the white screen with the 'Press SHIT for recovery'. I waited a while, then I unplugged the network cable. Nothing happened. Then I tried to hold down SHIT. A while longer I got the command line with an error that Recovery failed.

After reboot I could login and start GUI, but then I got an error (can remember what it was) about something couldn't be found.

**Comment by lurch** [comment] 2015-05-16 12:22
Duplicate of https://github.com/raspberrypi/noobs/issues/120#issuecomment-28561561

**Closed by lurch** 2015-05-16 12:22 UTC
Labels: duplicate
